only-office:
  doc-service: https://oo.biuaxia.cn
#  doc-service: http://192.168.25.139:9000
  # call-back-url: /onlyOffice/save
  # temp-storage: reports
  key: ""
spring:
  profiles:
    active: dev
